/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Correct (void)
{
  GtkWidget *Correct;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *npnts;
  GtkWidget *cnt_time;
  GtkWidget *dislo;
  GtkWidget *dishi;
  GtkWidget *guess;
  GtkWidget *step;
  GtkWidget *Close;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *resetval;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *uppres;
  GtkWidget *lowres;
  GtkWidget *uppcen;
  GtkWidget *lowcen;
  GtkWidget *enable_all;
  GtkWidget *hbox4;
  GtkWidget *sh_rems;
  GtkWidget *dis_outs;
  GtkWidget *hbox1;
  GtkWidget *Scan;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *fit;
  GtkWidget *correct;
  GtkWidget *Reset;
  GtkWidget *restore;
  GtkWidget *fname;

  Correct = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Correct), _("window1"));

  table1 = gtk_table_new (14, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (Correct), table1);

  label1 = gtk_label_new (_("Number of points in scan"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("Time to count at each point"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label3 = gtk_label_new (_("Thresh. val. to disable lower thresh."));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("Thresh. val. to disable upper thresh."));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Approx. value of peak height."));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_("Step size for scan"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  npnts = gtk_entry_new ();
  gtk_widget_show (npnts);
  gtk_table_attach (GTK_TABLE (table1), npnts, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cnt_time = gtk_entry_new ();
  gtk_widget_show (cnt_time);
  gtk_table_attach (GTK_TABLE (table1), cnt_time, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dislo = gtk_entry_new ();
  gtk_widget_show (dislo);
  gtk_table_attach (GTK_TABLE (table1), dislo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dishi = gtk_entry_new ();
  gtk_widget_show (dishi);
  gtk_table_attach (GTK_TABLE (table1), dishi, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  guess = gtk_entry_new ();
  gtk_widget_show (guess);
  gtk_table_attach (GTK_TABLE (table1), guess, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  step = gtk_entry_new ();
  gtk_widget_show (step);
  gtk_table_attach (GTK_TABLE (table1), step, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Close = gtk_button_new ();
  gtk_widget_show (Close);
  gtk_table_attach (GTK_TABLE (table1), Close, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Close), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Close window"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  label9 = gtk_label_new (_("DAC reset value"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  resetval = gtk_entry_new ();
  gtk_widget_show (resetval);
  gtk_table_attach (GTK_TABLE (table1), resetval, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("Upper resolution limit"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new (_("Lower resolution limit"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("Uper center limit"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("Lower center limit"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  uppres = gtk_entry_new ();
  gtk_widget_show (uppres);
  gtk_table_attach (GTK_TABLE (table1), uppres, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lowres = gtk_entry_new ();
  gtk_widget_show (lowres);
  gtk_table_attach (GTK_TABLE (table1), lowres, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  uppcen = gtk_entry_new ();
  gtk_widget_show (uppcen);
  gtk_table_attach (GTK_TABLE (table1), uppcen, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lowcen = gtk_entry_new ();
  gtk_widget_show (lowcen);
  gtk_table_attach (GTK_TABLE (table1), lowcen, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  enable_all = gtk_button_new_with_mnemonic (_("Enable all"));
  gtk_widget_show (enable_all);
  gtk_table_attach (GTK_TABLE (table1), enable_all, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table1), hbox4, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  sh_rems = gtk_button_new_with_mnemonic (_("Show remaining"));
  gtk_widget_show (sh_rems);
  gtk_box_pack_start (GTK_BOX (hbox4), sh_rems, TRUE, TRUE, 0);

  dis_outs = gtk_button_new_with_mnemonic (_("Disable outliers"));
  gtk_widget_show (dis_outs);
  gtk_box_pack_start (GTK_BOX (hbox4), dis_outs, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table1), hbox1, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  Scan = gtk_button_new ();
  gtk_widget_show (Scan);
  gtk_box_pack_start (GTK_BOX (hbox1), Scan, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Scan), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Scan"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  fit = gtk_button_new_with_mnemonic (_("Fit"));
  gtk_widget_show (fit);
  gtk_box_pack_start (GTK_BOX (hbox1), fit, FALSE, FALSE, 0);

  correct = gtk_button_new_with_mnemonic (_("Correct DACs"));
  gtk_widget_show (correct);
  gtk_box_pack_start (GTK_BOX (hbox1), correct, FALSE, FALSE, 0);

  Reset = gtk_button_new_with_mnemonic (_("Reset DACs"));
  gtk_widget_show (Reset);
  gtk_box_pack_start (GTK_BOX (hbox1), Reset, FALSE, FALSE, 0);

  restore = gtk_button_new_with_mnemonic (_("Restore DACs from file"));
  gtk_widget_show (restore);
  gtk_table_attach (GTK_TABLE (table1), restore, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  fname = gtk_entry_new ();
  gtk_widget_show (fname);
  gtk_table_attach (GTK_TABLE (table1), fname, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) npnts, "activate",
                    G_CALLBACK (on_npnts_activate),
                    NULL);
  g_signal_connect ((gpointer) cnt_time, "activate",
                    G_CALLBACK (on_cnt_time_activate),
                    NULL);
  g_signal_connect ((gpointer) dislo, "activate",
                    G_CALLBACK (on_dislo_activate),
                    NULL);
  g_signal_connect ((gpointer) dishi, "activate",
                    G_CALLBACK (on_dishi_activate),
                    NULL);
  g_signal_connect ((gpointer) guess, "activate",
                    G_CALLBACK (on_guess_activate),
                    NULL);
  g_signal_connect ((gpointer) step, "activate",
                    G_CALLBACK (on_step_activate),
                    NULL);
  g_signal_connect ((gpointer) Close, "clicked",
                    G_CALLBACK (on_Close_clicked),
                    NULL);
  g_signal_connect ((gpointer) resetval, "activate",
                    G_CALLBACK (on_resetval_activate),
                    NULL);
  g_signal_connect ((gpointer) uppres, "activate",
                    G_CALLBACK (on_uppres_activate),
                    NULL);
  g_signal_connect ((gpointer) lowres, "activate",
                    G_CALLBACK (on_lowres_activate),
                    NULL);
  g_signal_connect ((gpointer) uppcen, "activate",
                    G_CALLBACK (on_uppcen_activate),
                    NULL);
  g_signal_connect ((gpointer) lowcen, "activate",
                    G_CALLBACK (on_lowcen_activate),
                    NULL);
  g_signal_connect ((gpointer) enable_all, "clicked",
                    G_CALLBACK (on_enable_all_clicked),
                    NULL);
  g_signal_connect ((gpointer) sh_rems, "clicked",
                    G_CALLBACK (on_Show_remains_clicked),
                    NULL);
  g_signal_connect ((gpointer) dis_outs, "clicked",
                    G_CALLBACK (on_dis_outs_clicked),
                    NULL);
  g_signal_connect ((gpointer) Scan, "clicked",
                    G_CALLBACK (on_Scan_clicked),
                    NULL);
  g_signal_connect ((gpointer) fit, "clicked",
                    G_CALLBACK (on_Fit_clicked),
                    NULL);
  g_signal_connect ((gpointer) correct, "clicked",
                    G_CALLBACK (on_correct_clicked),
                    NULL);
  g_signal_connect ((gpointer) Reset, "clicked",
                    G_CALLBACK (on_Reset_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore, "clicked",
                    G_CALLBACK (on_restore_clicked),
                    NULL);
  g_signal_connect ((gpointer) fname, "activate",
                    G_CALLBACK (on_fname_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Correct, Correct, "Correct");
  GLADE_HOOKUP_OBJECT (Correct, table1, "table1");
  GLADE_HOOKUP_OBJECT (Correct, label1, "label1");
  GLADE_HOOKUP_OBJECT (Correct, label2, "label2");
  GLADE_HOOKUP_OBJECT (Correct, label3, "label3");
  GLADE_HOOKUP_OBJECT (Correct, label4, "label4");
  GLADE_HOOKUP_OBJECT (Correct, label5, "label5");
  GLADE_HOOKUP_OBJECT (Correct, label6, "label6");
  GLADE_HOOKUP_OBJECT (Correct, npnts, "npnts");
  GLADE_HOOKUP_OBJECT (Correct, cnt_time, "cnt_time");
  GLADE_HOOKUP_OBJECT (Correct, dislo, "dislo");
  GLADE_HOOKUP_OBJECT (Correct, dishi, "dishi");
  GLADE_HOOKUP_OBJECT (Correct, guess, "guess");
  GLADE_HOOKUP_OBJECT (Correct, step, "step");
  GLADE_HOOKUP_OBJECT (Correct, Close, "Close");
  GLADE_HOOKUP_OBJECT (Correct, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Correct, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Correct, image2, "image2");
  GLADE_HOOKUP_OBJECT (Correct, label8, "label8");
  GLADE_HOOKUP_OBJECT (Correct, label9, "label9");
  GLADE_HOOKUP_OBJECT (Correct, resetval, "resetval");
  GLADE_HOOKUP_OBJECT (Correct, label10, "label10");
  GLADE_HOOKUP_OBJECT (Correct, label11, "label11");
  GLADE_HOOKUP_OBJECT (Correct, label12, "label12");
  GLADE_HOOKUP_OBJECT (Correct, label13, "label13");
  GLADE_HOOKUP_OBJECT (Correct, uppres, "uppres");
  GLADE_HOOKUP_OBJECT (Correct, lowres, "lowres");
  GLADE_HOOKUP_OBJECT (Correct, uppcen, "uppcen");
  GLADE_HOOKUP_OBJECT (Correct, lowcen, "lowcen");
  GLADE_HOOKUP_OBJECT (Correct, enable_all, "enable_all");
  GLADE_HOOKUP_OBJECT (Correct, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Correct, sh_rems, "sh_rems");
  GLADE_HOOKUP_OBJECT (Correct, dis_outs, "dis_outs");
  GLADE_HOOKUP_OBJECT (Correct, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Correct, Scan, "Scan");
  GLADE_HOOKUP_OBJECT (Correct, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Correct, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Correct, image1, "image1");
  GLADE_HOOKUP_OBJECT (Correct, label7, "label7");
  GLADE_HOOKUP_OBJECT (Correct, fit, "fit");
  GLADE_HOOKUP_OBJECT (Correct, correct, "correct");
  GLADE_HOOKUP_OBJECT (Correct, Reset, "Reset");
  GLADE_HOOKUP_OBJECT (Correct, restore, "restore");
  GLADE_HOOKUP_OBJECT (Correct, fname, "fname");

  return Correct;
}

