caput det1:ai0.SCAN "Passive"
caput det1:ai1.SCAN "Passive"
caput det1:ai2.SCAN "Passive"
caput det1:ai3.SCAN "Passive"
caput det1:ai4.SCAN "Passive"
caput det1:ai5.SCAN "Passive"
caput det1:ai6.SCAN "Passive"
caput det1:ai7.SCAN "Passive"
